Fix issue involving segment 0
ScreepsPlus/node-agent pull request #10
Opened 2018-03-24 08:38 UTC by lurr

Yup, forgot one thing. Discovered this when I realized my stats weren't propagating properly; and I thought they were! >.>

2018-03-24 16:30 UTC, AlinaNova21 requested changes

2018-03-24 16:30 UTC, ags131 commented on package.json
> +  "version": "1.4.2",
Please don't increment version in PRs ;)

2018-03-25 01:02 UTC, lurr commented
package.json change reverted

2018-03-25 02:49 UTC, AlinaNova21 approved these changes

2018-03-25 02:49 UTC, merged